library(shiny)
library(Remdat)
#WORKS_081717_NowNewStuffStart
library(ggplot2)
#WORKS_081717_NowNewStuffEND

ui <- fluidPage(
  #titlePanel("Cost and Killed of Disasters")
  #sliderInput("num", "Choose a number:", 1, 100, 50),
  selectInput("country", "Country", c("Afghanistan"="Afghanistan",
               "Albania"="Albania",
              "Algeria"="Algeria",
              "American Samoa"="American Samoa",
              "Angola"="Angola",
              "Anguilla"="Anguilla",
              "Antigua and Barbuda"="Antigua and Barbuda",
              "Argentina"="Argentina",
              "Armenia"="Armenia",
              "Australia"="Australia",
              "Austria"="Austria",
              "Azerbaijan"="Azerbaijan",
              "Azores"="Azores",
              "Bahamas"="Bahamas",
              "Bahrain"="Bahrain",
              "Bangladesh"="Bangladesh",
              "Barbados"="Barbados",
              "Belarus"="Belarus",
              "Belgium"="Belgium",
              "Belize"="Belize",
              "Benin"="Benin",
              "Bermuda"="Bermuda",
              "Bhutan"="Bhutan",
              "Bolivia"="Bolivia",
              "Bosnia-Hercegovenia"="Bosnia-Hercegovenia",
              "Botswana"="Botswana",
              "Brazil"="Brazil",
              "Brunei Darussalam"="Brunei Darussalam",
              "Bulgaria"="Bulgaria",
              "Burkina Faso"="Burkina Faso",
              "Burundi"="Burundi",
              "Cambodia"="Cambodia",
              "Cameroon"="Cameroon",
              "Canada"="Canada",
              "Canary Is"="Canary Is",
              "Cape Verde Is"="Cape Verde Is",
              "Cayman Islands"="Cayman Islands",
              "Central African Rep"="Central African Rep",
              "Chad"="Chad",
              "Chile"="Chile",
              "China P Rep"="China P Rep",
              "Colombia"="Colombia",
              "Comoros"="Comoros",
              "Congo"="Congo",
              "Cook Is"="Cook Is",
              "Costa Rica"="Costa Rica",
              "Cote d_Ivoire"="Cote d_Ivoire",
              "Croatia"="Croatia",
              "Cuba"="Cuba",
              "Cyprus"="Cyprus",
              "Czech Rep"="Czech Rep",
              "Czechoslovakia"="Czechoslovakia",
              "Denmark"="Denmark",
              "Djibouti"="Djibouti",
              "Dominica"="Dominica",
              "Dominican Rep"="Dominican Rep",
              "East Timor"="East Timor",
              "Ecuador"="Ecuador",
              "Egypt"="Egypt",
              "El Salvador"="El Salvador",
              "Equatorial Guinea"="Equatorial Guinea",
              "Eritrea"="Eritrea",
              "Estonia"="Estonia",
              "Ethiopia"="Ethiopia",
              "Fiji"="Fiji",
              "Finland"="Finland",
              "France"="France",
              "French Guiana"="French Guiana",
              "French Polynesia"="French Polynesia",
              "Gabon"="Gabon",
              "Gambia The"="Gambia The",
              "Georgia"="Georgia",
              "Germany"="Germany",
              "Germany Dem Rep"="Germany Dem Rep",
              "Germany Fed Rep"="Germany Fed Rep",
              "Ghana"="Ghana",
              "Greece"="Greece",
              "Grenada"="Grenada",
              "Guadeloupe"="Guadeloupe",
              "Guam"="Guam",
              "Guatemala"="Guatemala",
              "Guinea"="Guinea",
              "Guinea Bissau"="Guinea Bissau",
              "Guyana"="Guyana",
              "Haiti"="Haiti",
              "Honduras"="Honduras",
              "Hong Kong (China)"="Hong Kong (China)",
              "Hungary"="Hungary",
              "Iceland"="Iceland",
              "India"="India",
              "Indonesia"="Indonesia",
              "Iran Islam Rep"="Iran Islam Rep",
              "Iraq"="Iraq",
              "Ireland"="Ireland",
              "Israel"="Israel",
              "Italy"="Italy",
              "Jamaica"="Jamaica",
              "Japan"="Japan",
              "Jordan"="Jordan",
              "Kazakhstan"="Kazakhstan",
              "Kenya"="Kenya",
              "Kiribati"="Kiribati",
              "Korea Dem P Rep"="Korea Dem P Rep",
              "Korea Rep"="Korea Rep",
              "Kuwait"="Kuwait",
              "Kyrgyzstan"="Kyrgyzstan",
              "Lao P Dem Rep"="Lao P Dem Rep",
              "Latvia"="Latvia",
              "Lebanon"="Lebanon",
              "Lesotho"="Lesotho",
              "Liberia"="Liberia",
              "Libyan Arab Jamah"="Libyan Arab Jamah",
              "Lithuania"="Lithuania",
              "Luxembourg"="Luxembourg",
              "Macau"="Macau",
              "Macedonia FRY"="Macedonia FRY",
              "Madagascar"="Madagascar",
              "Malawi"="Malawi",
              "Malaysia"="Malaysia",
              "Maldives"="Maldives",
              "Mali"="Mali",
              "Malta"="Malta",
              "Marshall Is"="Marshall Is",
              "Martinique"="Martinique",
              "Mauritania"="Mauritania",
              "Mauritius"="Mauritius",
              "Mayotte"="Mayotte",
              "Mexico"="Mexico",
              "Micronesia Fed States"="Micronesia Fed States",
              "Moldova Rep"="Moldova Rep",
              "Mongolia"="Mongolia",
              "Montenegro"="Montenegro",
              "Montserrat"="Montserrat",
              "Morocco"="Morocco",
              "Mozambique"="Mozambique",
              "Myanmar"="Myanmar",
              "Namibia"="Namibia",
              "Nepal"="Nepal",
              "Netherlands"="Netherlands",
              "Netherlands Antilles"="Netherlands Antilles",
              "New Caledonia"="New Caledonia",
              "New Zealand"="New Zealand",
              "Nicaragua"="Nicaragua",
              "Niger"="Niger",
              "Nigeria"="Nigeria",
              "Niue"="Niue",
              "Northern Mariana Is"="Northern Mariana Is",
              "Norway"="Norway",
              "Oman"="Oman",
              "Pakistan"="Pakistan",
              "Palau"="Palau",
              "Palestine (West Bank)"="Palestine (West Bank)",
              "Panama"="Panama",
              "Papua New Guinea"="Papua New Guinea",
              "Paraguay"="Paraguay",
              "Peru"="Peru",
              "Philippines"="Philippines",
              "Poland"="Poland",
              "Portugal"="Portugal",
              "Puerto Rico"="Puerto Rico",
              "Reunion"="Reunion",
              "Romania"="Romania",
              "Russia"="Russia",
              "Rwanda"="Rwanda",
              "Samoa"="Samoa",
              "Sao Tome et Principe"="Sao Tome et Principe",
              "Saudi Arabia"="Saudi Arabia",
              "Senegal"="Senegal",
              "Serbia"="Serbia",
              "Serbia Montenegro"="Serbia Montenegro",
              "Seychelles"="Seychelles",
              "Sierra Leone"="Sierra Leone",
              "Singapore"="Singapore",
              "Slovakia"="Slovakia",
              "Slovenia"="Slovenia",
              "Solomon Is"="Solomon Is",
              "Somalia"="Somalia",
              "South Africa"="South Africa",
              "Soviet Union"="Soviet Union",
              "Spain"="Spain",
              "Sri Lanka"="Sri Lanka",
              "St Helena"="St Helena",
              "St Kitts and Nevis"="St Kitts and Nevis",
              "St Lucia"="St Lucia",
              "St Vincent and The Grenadines"="St Vincent and The Grenadines",
              "St Vincent and the Grenadines"="St Vincent and the Grenadines",
              "Sudan"="Sudan",
              "Suriname"="Suriname",
              "Swaziland"="Swaziland",
              "Sweden"="Sweden",
              "Switzerland"="Switzerland",
              "Syrian Arab Rep"="Syrian Arab Rep",
              "Taiwan (China)"="Taiwan (China)",
              "Tajikistan"="Tajikistan",
              "Tanzania Uni Rep"="Tanzania Uni Rep",
              "Thailand"="Thailand",
              "Timor-Leste"="Timor-Leste",
              "Togo"="Togo",
              "Tokelau"="Tokelau",
              "Tonga"="Tonga",
              "Trinidad and Tobago"="Trinidad and Tobago",
              "Tunisia"="Tunisia",
              "Turkey"="Turkey",
              "Turkmenistan"="Turkmenistan",
              "Turks and Caicos Is"="Turks and Caicos Is",
              "Tuvalu"="Tuvalu",
              "Uganda"="Uganda",
              "Ukraine"="Ukraine",
              "United Arab Emirates"="United Arab Emirates",
              "United Kingdom"="United Kingdom",
              "United States"="United States",
              "Uruguay"="Uruguay",
              "Uzbekistan"="Uzbekistan",
              "Vanuatu"="Vanuatu",
              "Venezuela"="Venezuela",
              "Viet Nam"="Viet Nam",
              "Virgin Is (UK)"="Virgin Is (UK)",
              "Virgin Is (US)"="Virgin Is (US)",
              "Wallis "="Wallis ",
              "Wallis and Futuna Is"="Wallis and Futuna Is",
              "Yemen"="Yemen",
              "Yemen Arab Rep"="Yemen Arab Rep",
              "Yemen P Dem Rep"="Yemen P Dem Rep",
              "Yugoslavia"="Yugoslavia",
              "Zaire/Congo Dem Rep"="Zaire/Congo Dem Rep",
              "Zambia"="Zambia",
              "Zimbabwe"="Zimbabwe")),
  plotOutput("countryKilledYear"),
  selectInput("disasterType", "Disaster Type:",
              c("Air" = "Air",
                "Avalanche" = "Avalanche",
                "Bacterial Infectious Diseases" = "Bacterial Infectious Diseases",
                "Bush/Brush fire" = "Bush/Brush fire",
                "Chemical Spill" = "Chemical Spill",
                #"Cold Wave" = "Cold Wave",
                "Cold wave" = "Cold wave",
                "Collapse" = "Collapse",
                "Debris flow" = "Debris flow",
                "Drought" = "Drought",
                "Earthquake (ground shaking)" = "Earthquake (ground shaking)",
                "Explosion" = "Explosion",
                "Extratropical cyclone (winter storm)" = "Extratropical cyclone (winter storm)",
                "Extreme winter conditions" = "Extreme winter conditions",
                "Extratropical cyclone" = "Extratropical cyclone",
                "Famine" = "Famine",
                "Fire" = "Fire",
                #"Flash Flood" = "Flash Flood",
                "Flash flood" = "Flash flood",
                "Forest fire" = "Forest fire",
                "Gas Leak" = "Gas Leak",
                "General Flood" = "General Flood",
                "General flood" = "General flood",
                "General flood/Mudslide" = "General flood/Mudslide",
                #"Grasshopper" = "Grasshopper",
                #"Grasshopper/Locust" = "Grasshopper/Locust",
                "Heat wave" = "Heat wave",
                "Landslide" = "Landslide",
                "Local storm" = "Local storm",
                "Locust" = "Locust",
                "Oil Spill" = "Oil Spill",
                "Other" = "Other",
                "Parasitic Infectious Diseases" = "Parasitic Infectious Diseases",
                "Poisoning" = "Poisoning",
                "Radiation" = "Radiation",
                "Rail" = "Rail",
                "Road" = "Road",
                "Rockfall" = "Rockfall",
                "Scrub/grassland fire" = "Scrub/grassland fire",
                #"Storm surge/coastal Flood" = "Storm surge/coastal Flood",
                "Storm surge/coastal flood" = "Storm surge/coastal flood",
                "Subsidence" = "Subsidence",
                "Tropical cyclone" = "Tropical cyclone",
                "Tsunami" = "Tsunami",
                "Viral Infectious Diseases" = "Viral Infectious Diseases",
                "Volcanic eruption" = "Volcanic eruption",
                "Water" = "Water")),
  plotOutput("hist"),
  plotOutput("histCost"),
  #verbatimTextOutput("sum")
  verbatimTextOutput("sum")
)

server <- function(input, output) {
  #data2<-reactive({Remdat[which(Remdat$Country==input$country),]})
  data2<-reactive({Remdat[which(Remdat$Country==input$country & !is.na(Remdat$Killed)),]})
  data<-reactive({Remdat[which(Remdat$Sub_Type==input$disasterType),]})
  output$countryKilledYear<-renderPlot(
    #ggplot(Remdat[which(Remdat$Country=="Colombia" & !is.na(Remdat$Killed)),],
    # aes(x=substr(Start,0,4),y=log10(Killed),color=Type))+geom_point(alpha=0.2)
    #+geom_point(position="jitter")+ggtitle("Year v log10(Killed)")+xlab("Year")
    ggplot(data2(),aes(x=substr(Start,0,4),y=log10(Killed),color=Type))
    +geom_point(alpha=0.3)
    +geom_point(position="jitter")
    +ggtitle("Number Killed by Disaster Type")
    +xlab("Year")
  )
  output$hist <- renderPlot({
    #hist(Remdat[which(Remdat$Sub_Type==input$disasterType),]$Killed)
    #hist(Remdat[which(Remdat$Sub_Type==input$disasterType),]$Killed,breaks = 100)
    #WORKS_081717_hist(data()$Killed,breaks = 100)
    hist(data()$Killed,breaks = 100)
    #WORKS_081717_NowNewStuffStart
    
    #WORKS_081717_NowNewStuffEnd
    
  })
  output$histCost <- renderPlot({
    hist(data()$Cost,breaks = 100)
  })
  output$sum <- renderPrint({
    summary(data())
    #NOsummary(Remdat[which(Remdat$Sub_Type==input$diasterType),])
    #NOsum(Remdat[which(Remdat$Sub_Type==input$diasterType),])
    #NOsummary(Remdat[which(Remdat$Sub_Type==input$diasterType),],na.rm=T)
    #NOsummary(Remdat[which(Remdat$Sub_Type==input$diasterType & Remdat$Killed>=0),])
  })
}

shinyApp(ui = ui, server = server)

